---
name: System Connection Form
description: >
  Use this template to provide the necessary information required for sys-conn setup.
  It also provides a tracking list for actions an admins needs to perform.
title: "[Sys-Conn Request]: "
labels: "service request"
assignees:
  - boonwj
  - wykeith
body:
  - type: markdown
    attributes:
      value: |
        ## System Connection Setup Details
  - type: input
    id: dr-id
    attributes:
      label: Data Request ID(s)
      description: The Data Request (DR) ID(s) that will be used by this system connection.
      placeholder: DUMMY-2024-08-001, DUMMY-2024-05-005
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is this for (PRD / STG)
      options:
        - PRD
        - STG
    validations:
      required: true
  - type: dropdown
    id: sys-conn-type
    attributes:
      label: System Connection Type
      description: What type of system connection
      options:
        - SF/API (via Azure SPN)
        - SF (via Key Pair)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Service Principal Information 
        Azure SPN:
        - Service Principal Name: Use the same name as the Azure SPN (e.g. `spn-govtech-tcs-prd-apiuser`)
        - Service Principal ID: Use the Object ID (OID) of the Azure SPN. If required, query via Azure CLI.

        Key Pair:
        - Service Principal Name: Give it a meaningful name with dhuser prefix (e.g. `dhuser-govtech-tcs-prd-01)
        - Service Principal ID: Generate UUID4 value either via https://www.uuidgenerator.net/ or `python -c 'import uuid; print(uuid.uuid4())'`

  - type: input
    id: spn-name
    attributes:
      label: Service Principal Name
      description: The service principal name that will use the system connection
      placeholder: <spn|dhuser>-<agency>-<project>-<env>-<name>
    validations:
      required: true
  - type: input
    id: spn-id
    attributes:
      label: Service Principal ID
      description: The service principal login ID
    validations:
      required: true
  - type: input
    id: ip-whitelist
    attributes:
      label: System IP address(es)
      description: The IP address(es) used by the calling system
  - type: textarea
    id: public-key
    attributes:
      label: Public Key (if used)
      description: The public key that will be used for Key Pair authentication
  - type: textarea
    id: misc
    attributes:
      label: Other Information
      description: Any other information to provide for this system connection?
  - type: textarea
    id: admin-checklist
    attributes:
      label: Admin Checklist
      value: |
        ---
        ### (Azure SPN Only) AIS SRs for Authentication
        - [ ] Raise AIS SR to add new role in app registration
          - i.e. session:role:dr_id_lower_case
        - [ ] Raise AIS SR to grant SPN role in app
          - i.e. session:role:public & session:role:dr_id_lower_case
        - [ ] Store AIS SRs into DCS folder
          - `145 - TC Sensors / 7. System Connection / AIS Service Requests`
        
        ### (SF Only) Whitelist IPs on NSG
        - [ ] Whitelist system IP addresses on privatelink NSG

        ### (All) Configure sys-conn
        - [ ] PR setup notebook to  `notebooks/sys-conn/<env>/` in `tcs-core`: https://github.com/dsaidgovsg/tcs-core/tree/master/notebooks/sys-conn
        - [ ] Notify users 
        
        ## Email Template
        ### For API (SPN)
        > Access have been granted to:
        >
        > - SPN Name: spn-...
        > - Data Requests: DR_IDs

        ### For SF (SPN)
        > Access have been granted to:
        >
        > - SPN Name: spn-...
        > - Data Requests: DR_IDs
        > - Snowflake Details:
        >   - Database: ...
        >   - Schema: ...
        >   - Role: ...

        ### For SF (Key Pair)
        > Access have been granted to:
        >
        > - Name: dhuser-...
        > - User ID: UUID value assigned to user
        > - Data Requests: DR_IDs
        > - Snowflake Details:
        >   - Database: ...
        >   - Schema: ...
        >   - Role: ...
