name: Approval
run-name: ${{ github.event.inputs.title }}

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'title: title to be displayed in approval issue'
        required: true
        type: string
      body:
        description: 'body: content to be displayed in approval issue body'
        required: true
        type: string
      triggered_by:
        description: 'triggered_by: github user id of user requested approval'
        required: true
        type: string
      caller_repo:
        description: 'caller_repo: repository calling this workflow'
        required: true
        type: string
      run_id:
        description: 'run_id: run id of calling workflow'
        required: true
        type: string

jobs:
  seek_approval:
    runs-on: ubuntu-latest
    env:
      APPROVERS: "{\"ids\": [\"bnew11245\", \"boonwj\"]}"
    steps:
      - name: Create approvers
        run: |
          RUN_APPROVERS=$(echo ${{ env.APPROVERS }} | jq -cr '.ids | map(select(. | contains("${{ github.event.inputs.triggered_by }}") | not)) | join(",")')
          echo $RUN_APPROVERS
          echo "RUN_APPROVERS=$RUN_APPROVERS" >> "$GITHUB_ENV"

      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 10
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ env.RUN_APPROVERS }}
          minimum-approvals: 1
          issue-title: >-
            ${{ github.event.inputs.title }}

          issue-body: >
            Caller Repo | Called By | Calling Run URL

            --- | --- | ---

            ${{ github.event.inputs.caller_repo }} | @${{ github.event.inputs.triggered_by }} | [link](https://github.com/${{ github.event.inputs.caller_repo }}/actions/runs/${{ github.event.inputs.run_id }})

            ---

            ${{ github.event.inputs.body }}

          exclude-workflow-initiator-as-approver: true
          additional-approved-words: ''
          additional-denied-words: ''

  show_context:
    runs-on: ubuntu-latest
    steps:
      - name: Show All Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "${GITHUB_CONTEXT}"

