name: Approval Gate
run-name: ${{ github.event.inputs.title }}

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'title to be displayed in approval issue'
        required: true
        type: string
      body:
        description: 'content to be displayed in approval issue body'
        required: true
        type: string
      triggered_by:
        description: 'github user id of user requested approval'
        required: true
        type: string


jobs:
  seek_approval:
    runs-on: ubuntu-latest
    env:
      APPROVERS: ("boonwj" "bnew11245")
    steps:
      - name: Deny if triggered by admins
        if: ${{ contains(env.APPROVERS, github.event.inputs.triggered_by) }}
        run: |
          echo "::error::Triggering user cannot be in approver list"
          exit 1

      - name: Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 10
        with:
          secret: ${{ github.TOKEN }}
          approvers: join(env.APPROVERS, ',')
          minimum-approvals: 1
          issue-title: >-
            ${{ fromJSON(github.event.inputs.title) }}

          issue-body: >
            ${{ fromJSON(github.event.inputs.body) }}

          exclude-workflow-initiator-as-approver: true
          additional-approved-words: ''
          additional-denied-words: ''

  show_context:
    runs-on: ubuntu-latest
    steps:
      - name: Show All Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "${GITHUB_CONTEXT}"

