name: Deployment (docs)
run-name: ${{ inputs.env_type }} -- Deploy ${{ github.ref_name }}

# This is mock of the ui deployment

on:
  workflow_dispatch:
    inputs:
      env_type:
        description: 'env_type: target env to deploy to'
        required: true
        default: 'stg'
        type: choice
        options:
          - prd
          - stg
          - dev
          - sandbox

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check argument
        id: check_arg
        run: |
          env_type=${{ github.event.inputs.env_type }}
          deploy_app="docs"

          echo "env_type=${env_type}" >> $GITHUB_OUTPUT
          echo "env_type_cap=${env_type^^}" >> $GITHUB_OUTPUT
          echo "deploy_app=${deploy_app}" >> $GITHUB_OUTPUT

      - name: Store build time
        id: build_time
        run: |
          build_time=`date +%s%N | cut -b1-13`
          echo "build_time=${build_time}" >> $GITHUB_OUTPUT

      - name: Seek approval for PRD deployments
        if: ${{ github.event.inputs.env_type == 'prd' }}
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          repo: boonwj/testtesttest
          token: ${{ secrets.APPROVAL_PAT }}
          workflow: approval.yml
          ref: main
          inputs: '{"title": "Deploy ${{ steps.check_arg.outputs.env_type_cap }} ${{ steps.check_arg.outputs.deploy_app }} with ${{ github.ref_name }} (${{ github.ref_type }})", "body": "Workflow `${{ github.workflow }}` in `${{github.repository }}` requires approval to deploy `${{ github.ref_name }} (${{ github.ref_type }})` to `${{ steps.check_arg.outputs.deploy_app }}` in the `${{ steps.check_arg.outputs.env_type_cap }}` environment", "triggered_by": "${{ github.triggering_actor }}", "caller_repo": "${{ github.repository }}", "run_id": "${{ github.run_id }}"}'
          wait-for-completion-interval: 20s
          display-workflow-run-url-interval: 20s

      - name: Deployment
        run: |
          echo "Deployment will proceed"

      - name: Variables in run
        run: |
          echo "env_type: ${{ steps.check_arg.outputs.env_type }}"
          echo "env_type_cap: ${{ steps.check_arg.outputs.env_type_cap }}"

  context:
    runs-on: ubuntu-latest
    steps:
      - name: Show All Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "${GITHUB_CONTEXT}"
