name: Deployment (core)
run-name: Deploy to ${{ inputs.env_type }} by @${{ github.actor }}

# This is a dummy deployment for tcs-core

on:
  workflow_dispatch:
    inputs:
      env_type:
        description: 'Deploy to prd, stg, dev or sandbox'
        required: true
        default: 'stg'
        type: choice
        options:
          - prd
          - stg
          - dev
          - sandbox
      build_version:
        description: 'Set build version. Defaults to git commit id or tag value if empty.'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get deployment environment
        id: deploy_info
        run: |
          env_type="${{ github.event.inputs.env_type }}"
          build_version="${{ github.event.inputs.build_version }}"

          if [[ "${build_version}" == "" && ${{ github.ref_type }} == "tag" ]]; then
            build_version="${GITHUB_REF#refs/tags/v}"
          elif [[ "${build_version}" == "" ]]; then
            build_version="${GITHUB_SHA::8}"
          fi

          echo "::set-output name=env_type::${env_type}"
          echo "::set-output name=env_type_cap::${env_type^^}"
          echo "::set-output name=build_version::${build_version}"

      - name: Store build time
        id: build_time
        run: |
          build_time=`date +%s%N | cut -b1-13`
          echo "::set-output name=build_time::${build_time}"

      - name: Get all variables
        run: |
          echo "Build Time: ${{ steps.build_time.outputs.build_time }}"
          echo "Build Version: ${{ steps.deploy_info.outputs.build_version }}"
          echo "Env Type: ${{ steps.deploy_info.outputs.env_type }}"
          echo "Env Type Cap: ${{ steps.deploy_info.outputs.env_type_cap }}"

      - name: Approval for PRD deployments
        if: ${{ github.event.inputs.env_type == 'prd' }}
        uses: trstringer/manual-approval@v1
        timeout-minutes: 10
        with:
          secret: ${{ github.TOKEN }}
          approvers: boonwj,bnew11245
          minimum-approvals: 1
          issue-title: >-
            Deploy Core - ${{ github.ref_name }}
          issue-body: >
            Action | By | Environment | Ref Type | Ref Name

            --- | --- | --- | --- | ---

            ${{ github.workflow }} |
            @${{ github.triggering_actor }} |
            ${{ steps.check_arg.outputs.env_type_cap }} |
            ${{ github.ref_type }} |
            ${{ github.ref_name }}
          exclude-workflow-initiator-as-approver: true
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Deployment
        run: |
          echo "Deployment will continue"
          echo "${{ steps.deploy_info.outputs.env_type }}"
