name: Test run v1

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show environment v1
        run: env | grep ^GITHUB
      - name: Show ref v1
        run: echo "===============> Version from $GITHUB_REF"
      - name: Get current hash
        run: echo $(git rev-parse --short HEAD)
      - name: Get current hash v2
        run: echo $(git rev-parse --short "$GITHUB_SHA")
