name: Release

on:
  release:
    types: [published]

jobs:
  build-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0
        with:
          image: hub.docker.com/_/alpine:latest
          artifact-name: alpine.spdx
      - uses: anchore/sbom-action@v0
        with:
          image: hub.docker.com/_/python:3.8
          artifact-name: python.spdx
