name: "Integration Test"

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch'
    outputs:
      run_test: ${{ steps.result.outputs.to_test }}
    steps:
      - uses: actions/checkout@v3
        if: github.event.review.state == 'approved'
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v36
        id: changed-files
        if: github.event.review.state == 'approved'
        with:
          files: |
            api/backend/**/*.py
            api/backend/poetry.lock
            api/backend/pyproject.toml
      - if: (steps.changed-files.outputs.any_changed == 'true' && github.event.review.state == 'approved') || github.event_name == 'workflow_dispatch'
        id: result
        run: echo "to_test=true" >> $GITHUB_OUTPUT

  run_integration_test:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.run_test == 'true' }}
    steps:
      - run: echo "Run integration test"
