name: "Integration Test"
on:
  pull_request_review:
    types: [submitted]
    paths:
      - 'api/backend/**/*.py'
      - 'api/backend/poetry.lock'
      - 'api/backend/pyproject.toml'

jobs:
  run_integration_test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
