name: "Integration Test"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, unlabeled]
    paths:
      - 'api/backend/**/*.py'
      - 'api/backend/poetry.lock'
      - 'api/backend/pyproject.toml'
  pull_request_review:
    types: [submitted]

jobs:
  label_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          sync-labels: true
  run_integration_test:
    if: github.event.label.name == 'auto/need-int-test' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved and is of the correct label. I will run the integraiton test"
