name: "Integration Test"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, unlabeled]
  pull_request_review:
    types: [submitted]

jobs:
  run_integration_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          sync-labels: true
      - if: (contains(github.event.pull_request.labels.*.name, 'auto/need-integration-test') && github.event.review.state == 'approved') || github.event_name == 'workflow_dispatch'
        run: echo "This PR was approved and is of the correct label. OR it is manually triggered. I will run the integration test"
