name: "Integration Test"

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  run_integration_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: tj-actions/changed-files@v36
        id: changed-files
        if: github.event.review.state == 'approved'
        with:
          files: |
            'api/backend/**/*.py'
            'api/backend/poetry.lock'
            'api/backend/pyproject.toml'
      - if: (steps.changed-files.outputs.any_changed == 'true' && contains(github.event.pull_request.labels.*.name, 'auto/need-integration-test') && github.event.review.state == 'approved') || github.event_name == 'workflow_dispatch'
        run: echo "This PR was approved and is of the correct label. OR it is manually triggered. I will run the integration test"
