name: 'Pull notebooks branch on Databricks'
on:
  push:

jobs:
  pull-branch:
    runs-on: ubuntu-latest
    steps:
      #       - name: Pull PRD Databricks
      #         run: |
      #           REPO_PATH="/Repos/Production/tcs-core"  # This is case sensitive
      #           REPO_ID=$(curl --silent --request GET --header "Authorization: Bearer ${{ secrets.PRD_DATABRICKS_BEARER }}" --url "https://${{ secrets.PRD_DATABRICKS_INSTANCE }}/api/2.0/repos?path_prefix=${REPO_PATH}" | jq ".repos[0].id")
      #           STATUS=$(curl --silent --output /dev/stderr --write-out "%{http_code}" --request PATCH --header 'Authorization: Bearer ${{ secrets.PRD_DATABRICKS_BEARER }}' --data '{"branch": "master"}' --url 'https://${{ secrets.PRD_DATABRICKS_INSTANCE }}/api/2.0/repos/${REPO_ID}')
      #           if [[ ${STATUS} -ne 200 ]]; then
      #             echo "REPO_ID: ${REPO_ID}"
      #             echo "STATUS: ${STATUS}"
      #             exit 22  # Error out when HTTP response is not 200
      #           fi

      - name: Pull STG Databricks
        run: |
          REPO_PATH="/Repos/Staging/tcs-core"  # This is case sensitive
          REPO_ID=$(curl --silent --request GET --header "Authorization: Bearer ${{ secrets.STG_DATABRICKS_BEARER }}" --url "https://${{ secrets.STG_DATABRICKS_INSTANCE }}/api/2.0/repos?path_prefix=${REPO_PATH}" | jq ".repos[0].id")
          STATUS=$(curl --silent --output /dev/stderr --write-out "%{http_code}" --request PATCH --header "Authorization: Bearer ${{ secrets.STG_DATABRICKS_BEARER }}" --data "{"branch": "master"}" --url "https://${{ secrets.STG_DATABRICKS_INSTANCE }}/api/2.0/repos/${REPO_ID}")
          if [[ ${STATUS} -ne 200 ]]; then
            echo "REPO_ID: ${REPO_ID}"
            echo "STATUS: ${STATUS}"
            exit 22  # Error out when HTTP response is not 200
          fi
